/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /usr/bin/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
/bin/sh: 1: /home/daniel/python3.12: not found
nohup: ignoring input
Traceback (most recent call last):
  File "/home/daniel/repos/iot_streamlit/acquire_data.py", line 3, in <module>
    from arduino_detector import get_sensor_data  # Debes implementar esta funci√≥n
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'get_sensor_data' from 'arduino_detector' (/home/daniel/repos/iot_streamlit/arduino_detector.py)
nohup: ignoring input
Error conectando a PostgreSQL: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "iot_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "iot_user"

